---
abstract: 'DWIM file serialization/deserialization'
author:
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::Exception: '0'
  Test::More: '0.88'
  Test::Requires: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.031, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: File-Serialize
provides:
  File::Serialize:
    file: lib/File/Serialize.pm
    version: v0.2.0
requires:
  Class::Load: '0'
  Exporter::Tiny: '0'
  List::Util: '1.41'
  Path::Tiny: '0'
  parent: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/yanick/File-Serialize/issues
  homepage: https://github.com/yanick/File-Serialize
  repository: https://github.com/yanick/File-Serialize.git
version: 0.2.0
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
